/*
FORCES_MPC_GP_MAP0_DynGP_9 : A fast customized optimization solver.

Copyright (C) 2013-2025 EMBOTECH AG [info@embotech.com]. All rights reserved.


This software is intended for simulation and testing purposes only. 
Use of this software for any commercial purpose is prohibited.

This program is distributed in the hope that it will be useful.
EMBOTECH makes NO WARRANTIES with respect to the use of the software 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE. 

EMBOTECH shall not have any liability for any damage arising from the use
of the software.

This Agreement shall exclusively be governed by and interpreted in 
accordance with the laws of Switzerland, excluding its principles
of conflict of laws. The Courts of Zurich-City shall have exclusive 
jurisdiction in case of any dispute.

*/

/* Generated by FORCESPRO v6.4.0 on Wednesday, January 28, 2026 at 3:10:37 PM */
#ifndef FORCES_MPC_GP_MAP0_DynGP_9_MEMORY_H
#define FORCES_MPC_GP_MAP0_DynGP_9_MEMORY_H

#include "FORCES_MPC_GP_MAP0_DynGP_9.h"


/* MEMORY STRUCT --------------------------------------------------------*/

#ifdef __cplusplus
extern "C" {
#endif
extern FORCES_MPC_GP_MAP0_DynGP_9_mem * FORCES_MPC_GP_MAP0_DynGP_9_internal_mem(solver_int32_unsigned i_mem);
#ifdef __cplusplus
}
#endif
#endif /* MEMORY_H */
