/**:
  ros__parameters:
    port: "/dev/ttyACM0"
    brake_max: 200000.0
    brake_min: -20000.0
    current_max: 100.0
    current_min: 0.0
    duty_cycle_max: 0.0
    duty_cycle_min: 0.0
    position_max: 0.0
    position_min: 0.0
    servo_max: 0.85
    servo_min: 0.15
    speed_max: 23250.0
    speed_min: -23250.0
    # VESC conversion parameters
    speed_to_erpm_gain: 4614.0
    speed_to_erpm_offset: 0.0
    steering_angle_to_servo_gain: -1.2135
    steering_angle_to_servo_offset: 0.5304
    wheelbase: 0.33
