/*
FORCES_MPC_GP_MAP0_DynGP_3 : A fast customized optimization solver.

Copyright (C) 2013-2025 EMBOTECH AG [info@embotech.com]. All rights reserved.


This software is intended for simulation and testing purposes only. 
Use of this software for any commercial purpose is prohibited.

This program is distributed in the hope that it will be useful.
EMBOTECH makes NO WARRANTIES with respect to the use of the software 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE. 

EMBOTECH shall not have any liability for any damage arising from the use
of the software.

This Agreement shall exclusively be governed by and interpreted in 
accordance with the laws of Switzerland, excluding its principles
of conflict of laws. The Courts of Zurich-City shall have exclusive 
jurisdiction in case of any dispute.

*/

/* Generated by FORCESPRO v6.4.0 on Wednesday, January 28, 2026 at 11:21:22 AM */
#ifndef FORCES_MPC_GP_MAP0_DynGP_3_H
#define FORCES_MPC_GP_MAP0_DynGP_3_H

#ifndef SOLVER_STDIO_H
#define SOLVER_STDIO_H
#include <stdio.h>
#endif
#ifndef SOLVER_STRING_H
#define SOLVER_STRING_H
#include <string.h>
#endif


#ifndef SOLVER_STANDARD_TYPES
#define SOLVER_STANDARD_TYPES

typedef signed char solver_int8_signed;
typedef unsigned char solver_int8_unsigned;
typedef char solver_int8_default;
typedef signed short int solver_int16_signed;
typedef unsigned short int solver_int16_unsigned;
typedef short int solver_int16_default;
typedef signed int solver_int32_signed;
typedef unsigned int solver_int32_unsigned;
typedef int solver_int32_default;
typedef signed long long int solver_int64_signed;
typedef unsigned long long int solver_int64_unsigned;
typedef long long int solver_int64_default;

#endif


/* DATA TYPE ------------------------------------------------------------*/
typedef double FORCES_MPC_GP_MAP0_DynGP_3_float;
typedef double FORCES_MPC_GP_MAP0_DynGP_3_ldl_s_float;
typedef double FORCES_MPC_GP_MAP0_DynGP_3_ldl_r_float;
typedef double FORCES_MPC_GP_MAP0_DynGP_3_callback_float;

typedef double FORCES_MPC_GP_MAP0_DynGP_3interface_float;

/* SOLVER SETTINGS ------------------------------------------------------*/

/* MISRA-C compliance */
#ifndef MISRA_C_FORCES_MPC_GP_MAP0_DynGP_3
#define MISRA_C_FORCES_MPC_GP_MAP0_DynGP_3 (0)
#endif

/* restrict code */
#ifndef RESTRICT_CODE_FORCES_MPC_GP_MAP0_DynGP_3
#define RESTRICT_CODE_FORCES_MPC_GP_MAP0_DynGP_3 (0)
#endif

/* print level */
#ifndef SET_PRINTLEVEL_FORCES_MPC_GP_MAP0_DynGP_3
#define SET_PRINTLEVEL_FORCES_MPC_GP_MAP0_DynGP_3    (0)
#endif

/* timing */
#ifndef SET_TIMING_FORCES_MPC_GP_MAP0_DynGP_3
#define SET_TIMING_FORCES_MPC_GP_MAP0_DynGP_3    (1)
#endif

/* Numeric Warnings */
/* #define PRINTNUMERICALWARNINGS */

/* maximum number of iterations  */
#define SET_MAXIT_FORCES_MPC_GP_MAP0_DynGP_3			(700)	

/* scaling factor of line search (FTB rule) */
#define SET_FLS_SCALE_FORCES_MPC_GP_MAP0_DynGP_3		(FORCES_MPC_GP_MAP0_DynGP_3_float)(0.99)      

/* maximum number of supported elements in the filter */
#define MAX_FILTER_SIZE_FORCES_MPC_GP_MAP0_DynGP_3	(700) 

/* whether callback return values should be checked */
#define EXTFUNC_RETURN_FORCES_MPC_GP_MAP0_DynGP_3 (0)

/* SOLVER RETURN CODES----------------------------------------------------------*/
/* solver has converged within desired accuracy */
#define OPTIMAL_FORCES_MPC_GP_MAP0_DynGP_3      (1)

/* maximum number of iterations has been reached */
#define MAXITREACHED_FORCES_MPC_GP_MAP0_DynGP_3 (0)

/* solver has stopped due to a timeout */
#define TIMEOUT_FORCES_MPC_GP_MAP0_DynGP_3   (2)

/* solver stopped externally */
#define EXIT_EXTERNAL_FORCES_MPC_GP_MAP0_DynGP_3 (3)

/* wrong number of inequalities error */
#define INVALID_NUM_INEQ_ERROR_FORCES_MPC_GP_MAP0_DynGP_3  (-4)

/* factorization error */
#define FACTORIZATION_ERROR_FORCES_MPC_GP_MAP0_DynGP_3   (-5)

/* NaN encountered in function evaluations */
#define BADFUNCEVAL_FORCES_MPC_GP_MAP0_DynGP_3  (-6)

/* no progress in method possible */
#define NOPROGRESS_FORCES_MPC_GP_MAP0_DynGP_3   (-7)

/* regularization error */
#define REGULARIZATION_ERROR_FORCES_MPC_GP_MAP0_DynGP_3   (-9)

/* invalid values in parameters */
#define PARAM_VALUE_ERROR_FORCES_MPC_GP_MAP0_DynGP_3   (-11)

/* too small timeout given */
#define INVALID_TIMEOUT_FORCES_MPC_GP_MAP0_DynGP_3   (-12)

/* thread error */
#define THREAD_FAILURE_FORCES_MPC_GP_MAP0_DynGP_3  (-98)

/* locking mechanism error */
#define LOCK_FAILURE_FORCES_MPC_GP_MAP0_DynGP_3  (-99)

/* licensing error - solver not valid on this machine */
#define LICENSE_ERROR_FORCES_MPC_GP_MAP0_DynGP_3  (-100)

/* Insufficient number of internal memory instances.
 * Increase codeoptions.max_num_mem. */
#define MEMORY_INVALID_FORCES_MPC_GP_MAP0_DynGP_3 (-101)

/* Number of threads larger than specified.
 * Increase codeoptions.nlp.max_num_threads. */
#define NUMTHREADS_INVALID_FORCES_MPC_GP_MAP0_DynGP_3 (-102)

/* invalid value (<= -100) returned by external function */
#define INVALIDFUNCEXIT_FORCES_MPC_GP_MAP0_DynGP_3 (-200)

/* bad value returned by external function */
#define BADFUNCEXIT_FORCES_MPC_GP_MAP0_DynGP_3(status) (status > -100? status - 200 : INVALIDFUNCEXIT_FORCES_MPC_GP_MAP0_DynGP_3)

/* invalid value (<= -100) returned by external parallel implementation */
#define INVALIDPARALLELEXIT_FORCES_MPC_GP_MAP0_DynGP_3 (-300)

/* bad value returned by external parallel implementation */
#define BADPARALLELEXIT_FORCES_MPC_GP_MAP0_DynGP_3(status) (status > -100? status - 300 : INVALIDPARALLELEXIT_FORCES_MPC_GP_MAP0_DynGP_3)

/* INTEGRATORS RETURN CODE ------------*/
/* Integrator ran successfully */
#define INTEGRATOR_SUCCESS (11)
/* Number of steps set by user exceeds maximum number of steps allowed */
#define INTEGRATOR_MAXSTEPS_EXCEEDED (12)


/* MEMORY STRUCT --------------------------------------------------------*/
typedef struct FORCES_MPC_GP_MAP0_DynGP_3_mem FORCES_MPC_GP_MAP0_DynGP_3_mem;
#ifdef __cplusplus
extern "C" {
#endif
/* MEMORY STRUCT --------------------------------------------------------*/
extern FORCES_MPC_GP_MAP0_DynGP_3_mem * FORCES_MPC_GP_MAP0_DynGP_3_external_mem(void * mem_ptr, solver_int32_unsigned i_mem, size_t mem_size);
extern size_t FORCES_MPC_GP_MAP0_DynGP_3_get_mem_size( void );
extern size_t FORCES_MPC_GP_MAP0_DynGP_3_get_const_size( void );
#ifdef __cplusplus
}
#endif

/* PARAMETERS -----------------------------------------------------------*/
/* fill this with data before calling the solver! */
typedef struct
{
    /* vector of size 6 */
    FORCES_MPC_GP_MAP0_DynGP_3_float xinit[6];

    /* vector of size 160 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x0[160];

    /* vector of size 160 */
    FORCES_MPC_GP_MAP0_DynGP_3_float all_parameters[160];


} FORCES_MPC_GP_MAP0_DynGP_3_params;


/* OUTPUTS --------------------------------------------------------------*/
/* the desired variables are put here by the solver */
typedef struct
{
    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x01[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x02[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x03[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x04[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x05[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x06[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x07[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x08[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x09[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x10[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x11[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x12[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x13[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x14[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x15[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x16[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x17[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x18[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x19[8];

    /* column vector of length 8 */
    FORCES_MPC_GP_MAP0_DynGP_3_float x20[8];


} FORCES_MPC_GP_MAP0_DynGP_3_output;


/* SOLVER INFO ----------------------------------------------------------*/
/* diagnostic data from last interior point step */
typedef struct
{
    /* scalar: iteration number */
    solver_int32_default it;

    /* scalar: number of iterations needed to optimality (branch-and-bound) */
    solver_int32_default it2opt;

    /* scalar: inf-norm of equality constraint residuals */
    FORCES_MPC_GP_MAP0_DynGP_3_float res_eq;

    /* scalar: inf-norm of inequality constraint residuals */
    FORCES_MPC_GP_MAP0_DynGP_3_float res_ineq;

    /* scalar: norm of stationarity condition */
    FORCES_MPC_GP_MAP0_DynGP_3_float rsnorm;

    /* scalar: max of all complementarity violations */
    FORCES_MPC_GP_MAP0_DynGP_3_float rcompnorm;

    /* scalar: primal objective */
    FORCES_MPC_GP_MAP0_DynGP_3_float pobj;

    /* scalar: dual objective */
    FORCES_MPC_GP_MAP0_DynGP_3_float dobj;

    /* scalar: duality gap := pobj - dobj */
    FORCES_MPC_GP_MAP0_DynGP_3_float dgap;

    /* scalar: relative duality gap := |dgap / pobj | */
    FORCES_MPC_GP_MAP0_DynGP_3_float rdgap;

    /* scalar: duality measure */
    FORCES_MPC_GP_MAP0_DynGP_3_float mu;

    /* scalar: duality measure (after affine step) */
    FORCES_MPC_GP_MAP0_DynGP_3_float mu_aff;

    /* scalar: centering parameter */
    FORCES_MPC_GP_MAP0_DynGP_3_float sigma;

    /* scalar: number of backtracking line search steps (affine direction) */
    solver_int32_default lsit_aff;

    /* scalar: number of backtracking line search steps (combined direction) */
    solver_int32_default lsit_cc;

    /* scalar: step size (affine direction) */
    FORCES_MPC_GP_MAP0_DynGP_3_float step_aff;

    /* scalar: step size (combined direction) */
    FORCES_MPC_GP_MAP0_DynGP_3_float step_cc;

    /* scalar: total solve time */
    FORCES_MPC_GP_MAP0_DynGP_3_float solvetime;

    /* scalar: time spent in function evaluations */
    FORCES_MPC_GP_MAP0_DynGP_3_float fevalstime;

    /* column vector of length 8: solver ID of FORCESPRO solver */
    solver_int32_default solver_id[8];


} FORCES_MPC_GP_MAP0_DynGP_3_info;







/* SOLVER FUNCTION DEFINITION -------------------------------------------*/
/* Time of Solver Generation: (UTC) Wednesday, January 28, 2026 11:21:26 AM */
/* User License expires on: (UTC) Tuesday, September 15, 2026 10:00:00 PM (approx.) (at the time of code generation) */
/* Solver Static License expires on: (UTC) Tuesday, September 15, 2026 10:00:00 PM (approx.) */
/* Solver Id: 7e44522f-5b2f-473d-ab2d-1dfbab7ffad6 */
/* Host Compiler Version: d76500f0 */
/* Target Compiler Version: unused */
/* examine exitflag before using the result! */
#ifdef __cplusplus
extern "C" {
#endif		

typedef solver_int32_default (*FORCES_MPC_GP_MAP0_DynGP_3_extfunc)(FORCES_MPC_GP_MAP0_DynGP_3_float* x, FORCES_MPC_GP_MAP0_DynGP_3_float* y, FORCES_MPC_GP_MAP0_DynGP_3_float* lambda, FORCES_MPC_GP_MAP0_DynGP_3_float* params, FORCES_MPC_GP_MAP0_DynGP_3_float* pobj, FORCES_MPC_GP_MAP0_DynGP_3_float* g, FORCES_MPC_GP_MAP0_DynGP_3_float* c, FORCES_MPC_GP_MAP0_DynGP_3_float* Jeq, FORCES_MPC_GP_MAP0_DynGP_3_float* h, FORCES_MPC_GP_MAP0_DynGP_3_float* Jineq, FORCES_MPC_GP_MAP0_DynGP_3_float* H, solver_int32_default stage, solver_int32_default iterations, solver_int32_default threadID);

extern solver_int32_default FORCES_MPC_GP_MAP0_DynGP_3_solve(FORCES_MPC_GP_MAP0_DynGP_3_params *params, FORCES_MPC_GP_MAP0_DynGP_3_output *output, FORCES_MPC_GP_MAP0_DynGP_3_info *info, FORCES_MPC_GP_MAP0_DynGP_3_mem *mem, FILE *fs, FORCES_MPC_GP_MAP0_DynGP_3_extfunc evalextfunctions_FORCES_MPC_GP_MAP0_DynGP_3);











#ifdef __cplusplus
}
#endif

#endif
