

#ifndef FORCES_MPC_GP_MAP0_DYNGP_3_MODEL_H
#include "include/FORCES_MPC_GP_MAP0_DynGP_3.h"
#define FORCES_MPC_GP_MAP0_DYNGP_3_MODEL_H
/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real FORCES_MPC_GP_MAP0_DynGP_3_float
#endif

#ifndef casadi_int
#define casadi_int solver_int32_default
#endif

int FORCES_MPC_GP_MAP0_DynGP_3_objective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
const casadi_int* FORCES_MPC_GP_MAP0_DynGP_3_objective_0_sparsity_out(casadi_int i);
int FORCES_MPC_GP_MAP0_DynGP_3_objective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FORCES_MPC_GP_MAP0_DynGP_3_objective_0_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define FORCES_MPC_GP_MAP0_DynGP_3_objective_0_SZ_ARG 2
#define FORCES_MPC_GP_MAP0_DynGP_3_objective_0_SZ_RES 2
#define FORCES_MPC_GP_MAP0_DynGP_3_objective_0_SZ_IW 0
#define FORCES_MPC_GP_MAP0_DynGP_3_objective_0_SZ_W 6
int FORCES_MPC_GP_MAP0_DynGP_3_dynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
const casadi_int* FORCES_MPC_GP_MAP0_DynGP_3_dynamics_0_sparsity_out(casadi_int i);
int FORCES_MPC_GP_MAP0_DynGP_3_dynamics_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FORCES_MPC_GP_MAP0_DynGP_3_dynamics_0_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define FORCES_MPC_GP_MAP0_DynGP_3_dynamics_0_SZ_ARG 2
#define FORCES_MPC_GP_MAP0_DynGP_3_dynamics_0_SZ_RES 2
#define FORCES_MPC_GP_MAP0_DynGP_3_dynamics_0_SZ_IW 0
#define FORCES_MPC_GP_MAP0_DynGP_3_dynamics_0_SZ_W 584
int FORCES_MPC_GP_MAP0_DynGP_3_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
const casadi_int* FORCES_MPC_GP_MAP0_DynGP_3_objective_1_sparsity_out(casadi_int i);
int FORCES_MPC_GP_MAP0_DynGP_3_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FORCES_MPC_GP_MAP0_DynGP_3_objective_1_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define FORCES_MPC_GP_MAP0_DynGP_3_objective_1_SZ_ARG 2
#define FORCES_MPC_GP_MAP0_DynGP_3_objective_1_SZ_RES 2
#define FORCES_MPC_GP_MAP0_DynGP_3_objective_1_SZ_IW 0
#define FORCES_MPC_GP_MAP0_DynGP_3_objective_1_SZ_W 6
#ifdef __cplusplus
} /* extern "C" */
#endif
#endif