/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real FORCES_MPC_MAP0_DynGP_float
#endif

#ifndef casadi_int
#define casadi_int solver_int32_default
#endif

int FORCES_MPC_MAP0_DynGP_objective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int FORCES_MPC_MAP0_DynGP_objective_0_alloc_mem(void);
int FORCES_MPC_MAP0_DynGP_objective_0_init_mem(int mem);
void FORCES_MPC_MAP0_DynGP_objective_0_free_mem(int mem);
int FORCES_MPC_MAP0_DynGP_objective_0_checkout(void);
void FORCES_MPC_MAP0_DynGP_objective_0_release(int mem);
void FORCES_MPC_MAP0_DynGP_objective_0_incref(void);
void FORCES_MPC_MAP0_DynGP_objective_0_decref(void);
casadi_int FORCES_MPC_MAP0_DynGP_objective_0_n_in(void);
casadi_int FORCES_MPC_MAP0_DynGP_objective_0_n_out(void);
casadi_real FORCES_MPC_MAP0_DynGP_objective_0_default_in(casadi_int i);
const char* FORCES_MPC_MAP0_DynGP_objective_0_name_in(casadi_int i);
const char* FORCES_MPC_MAP0_DynGP_objective_0_name_out(casadi_int i);
const casadi_int* FORCES_MPC_MAP0_DynGP_objective_0_sparsity_in(casadi_int i);
const casadi_int* FORCES_MPC_MAP0_DynGP_objective_0_sparsity_out(casadi_int i);
int FORCES_MPC_MAP0_DynGP_objective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FORCES_MPC_MAP0_DynGP_objective_0_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define FORCES_MPC_MAP0_DynGP_objective_0_SZ_ARG 2
#define FORCES_MPC_MAP0_DynGP_objective_0_SZ_RES 2
#define FORCES_MPC_MAP0_DynGP_objective_0_SZ_IW 0
#define FORCES_MPC_MAP0_DynGP_objective_0_SZ_W 6
int FORCES_MPC_MAP0_DynGP_dynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int FORCES_MPC_MAP0_DynGP_dynamics_0_alloc_mem(void);
int FORCES_MPC_MAP0_DynGP_dynamics_0_init_mem(int mem);
void FORCES_MPC_MAP0_DynGP_dynamics_0_free_mem(int mem);
int FORCES_MPC_MAP0_DynGP_dynamics_0_checkout(void);
void FORCES_MPC_MAP0_DynGP_dynamics_0_release(int mem);
void FORCES_MPC_MAP0_DynGP_dynamics_0_incref(void);
void FORCES_MPC_MAP0_DynGP_dynamics_0_decref(void);
casadi_int FORCES_MPC_MAP0_DynGP_dynamics_0_n_in(void);
casadi_int FORCES_MPC_MAP0_DynGP_dynamics_0_n_out(void);
casadi_real FORCES_MPC_MAP0_DynGP_dynamics_0_default_in(casadi_int i);
const char* FORCES_MPC_MAP0_DynGP_dynamics_0_name_in(casadi_int i);
const char* FORCES_MPC_MAP0_DynGP_dynamics_0_name_out(casadi_int i);
const casadi_int* FORCES_MPC_MAP0_DynGP_dynamics_0_sparsity_in(casadi_int i);
const casadi_int* FORCES_MPC_MAP0_DynGP_dynamics_0_sparsity_out(casadi_int i);
int FORCES_MPC_MAP0_DynGP_dynamics_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FORCES_MPC_MAP0_DynGP_dynamics_0_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define FORCES_MPC_MAP0_DynGP_dynamics_0_SZ_ARG 2
#define FORCES_MPC_MAP0_DynGP_dynamics_0_SZ_RES 2
#define FORCES_MPC_MAP0_DynGP_dynamics_0_SZ_IW 0
#define FORCES_MPC_MAP0_DynGP_dynamics_0_SZ_W 169
int FORCES_MPC_MAP0_DynGP_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int FORCES_MPC_MAP0_DynGP_objective_1_alloc_mem(void);
int FORCES_MPC_MAP0_DynGP_objective_1_init_mem(int mem);
void FORCES_MPC_MAP0_DynGP_objective_1_free_mem(int mem);
int FORCES_MPC_MAP0_DynGP_objective_1_checkout(void);
void FORCES_MPC_MAP0_DynGP_objective_1_release(int mem);
void FORCES_MPC_MAP0_DynGP_objective_1_incref(void);
void FORCES_MPC_MAP0_DynGP_objective_1_decref(void);
casadi_int FORCES_MPC_MAP0_DynGP_objective_1_n_in(void);
casadi_int FORCES_MPC_MAP0_DynGP_objective_1_n_out(void);
casadi_real FORCES_MPC_MAP0_DynGP_objective_1_default_in(casadi_int i);
const char* FORCES_MPC_MAP0_DynGP_objective_1_name_in(casadi_int i);
const char* FORCES_MPC_MAP0_DynGP_objective_1_name_out(casadi_int i);
const casadi_int* FORCES_MPC_MAP0_DynGP_objective_1_sparsity_in(casadi_int i);
const casadi_int* FORCES_MPC_MAP0_DynGP_objective_1_sparsity_out(casadi_int i);
int FORCES_MPC_MAP0_DynGP_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FORCES_MPC_MAP0_DynGP_objective_1_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define FORCES_MPC_MAP0_DynGP_objective_1_SZ_ARG 2
#define FORCES_MPC_MAP0_DynGP_objective_1_SZ_RES 2
#define FORCES_MPC_MAP0_DynGP_objective_1_SZ_IW 0
#define FORCES_MPC_MAP0_DynGP_objective_1_SZ_W 6
#ifdef __cplusplus
} /* extern "C" */
#endif
